### ISSUE TITLE
Splash Damage form swords

### ISSUE THREAD

**Issue by ItzMotiz** [SattesKrokodil/Adventure-Pack#13]
**Is your feature request related to a problem? Please describe.**
it isn't a problem really. When you hit a tamed wolf you do no damage, but when you hit an enemy the sweeping damage from the sword hits your wolf.
**Describe the solution you'd like**
Can you make it where sweeping damage doesn't hurt your tamed wolves?
**Describe alternatives you've considered**
coding.
**Additional context**

**Comment by SattesKrokodil** [comment]
this is more an isssue of the mod that makes pets immune to damage can't o much there
