### ISSUE TITLE
Uncraftable Iron chests from Acacia/Oak chests

### ISSUE THREAD

**Issue by Mendanbar** [SattesKrokodil/Adventure-Pack#16]
**Describe the bug**
Some of the custom chest variants are unable to be crafted into iron chests directly (though creating an iron chest upgrade and applying it to the placed chest works)

**To Reproduce**
1. Make an acacia chest
2. Surround it with iron in the crafting grid to try to make an iron chest
3. Recipe reads as invalid

**Expected behavior**
All variant chests should be able to be directly crafted into iron chests

**Screenshots**
![2021-03-26_11 03 02 copy](https://user-images.githubusercontent.com/10580609/112674706-7bfb5300-8e23-11eb-8783-7cba3bfbf3ea.png)
![2021-03-26_11 03 19 copy](https://user-images.githubusercontent.com/10580609/112674731-83226100-8e23-11eb-93dd-e99e52f701ba.png)
![2021-03-26_11 03 32 copy](https://user-images.githubusercontent.com/10580609/112674747-87e71500-8e23-11eb-9f16-1eeb2b6126b1.png)
![2021-03-26_11 03 39 copy](https://user-images.githubusercontent.com/10580609/112674765-8c133280-8e23-11eb-87a8-4d90d0b7676d.png)

**Desktop (please complete the following information):**
 - Launcher: GD
 - Version: 4.3.2
 - OS: MacOS
 
**Additional context**

**Comment by SattesKrokodil** [comment]
Storage systems are now integrated in the profession system; I will check all recipes that aren't and add missing ones
