### ISSUE TITLE
Silver Key easily destroyed [FEEDBACK]

### ISSUE THREAD

**Issue by nin10donerd** [SattesKrokodil/Adventure-Pack#18]
### Negative:
The silver key dropped from Magma Tower bosses can be destroyed by either hitting the charge back at the boss or it falling into the flames created by the golems charges. Please consider making this drop immune to fire / or not destroyable and / or craft able

**Comment by SattesKrokodil** [comment]
With the next Dungeons of Exile update the Magma/Fire Golems will be replaced with ice! So this won't happen again (=

**Comment by SattesKrokodil** [comment]
Silver keys are fireproof now
